### ISSUE TITLE
wschat-3.0.3.jar should place in https://repo.grails.org/grails/core/org/grails/plugins/wschat/3.0.3/

### ISSUE THREAD

**Issue by hanyou** [vahidhedayati/grails-wschat-plugin#10]
![image](https://cloud.githubusercontent.com/assets/2518751/10846726/b758340e-7f4c-11e5-8724-64567abb0bce.png)

wschat-3.0.3.jar should place in https://repo.grails.org/grails/core/org/grails/plugins/wschat/3.0.3/
now
you put it in https://repo.grails.org/grails/core/  ,so I can't install this plugin

**Comment by vahidhedayati** [comment]
Trying to rectify the issue, I wonder what happens if you try:
```
compile ":wschat:3.0.3"
```
or
```
compile "wschat:3.0.3"
```

**Comment by vahidhedayati** [comment]
https://repo.grails.org/grails/core/org/grails/plugins/grails-wschat-plugin/

Think it should be fixed  now

**Comment by akiong** [comment]
hi...i see this your link.. 
https://repo.grails.org/grails/core/org/grails/plugins/grails-wschat-plugin/

after repo.grails.org/grails/core/ *then* **org/grails/plugins** *then* **grails-wschat-plugin**

so i tried to create a new project then try to install wschat like this..

**compile "org.grails.plugins:grails-wschat-plugin:3.0.3" **

then i success install wschat..

C:\Users\User\Documents\wschatTest>grails run-app
> Configuring > 0/1 projects > root project > Resolving dependencies ':classpath
1/1 projects > Resolving dependencies ':agent' > Resolving dependencies ':versio

BUILD SUCCESSFUL

Total time: 2.371 secs
> Resolving dependencies ':testRuntime' > Resolving dependencies 'detachedConfig
Download https://repo.grails.org/grails/core/org/grails/plugins/grails-wschat-pl
ugin/3.0.3/grails-wschat-plugin-3.0.3.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/grails-wschat-pl
| Running application...
Grails application running at http://localhost:8080 in environment: development

**Comment by vahidhedayati** [comment]
ok thanks for your input, I will take a look at this before releasing the next version and I will update it to this method for the 3.0.3 version in the docs.

**Comment by vahidhedayati** [comment]
3.0.4 has been released and should hopefully be cured from this issue. It has just been released and I expect by tomorrow sometime it will start appearing in the correct folder under that url

**Comment by vahidhedayati** [comment]
This is now resolved, please re-open if you feel it needs resolving since its moved way on since 3.0.3 anyways
