### ISSUE TITLE
sometimes button close chat dialog not work

### ISSUE THREAD

**Issue by akiong** [vahidhedayati/grails-wschat-plugin#12]
hi...i tried your 3.0.8 version

i don't know why, but sometimes i cannot close that chat dialog and i dont get any log with firebug or dev tools..

![close button](https://lh4.googleusercontent.com/-CyvxMNlmpA8/VkG_pc3CnPI/AAAAAAAAAq0/u2V5hNxgkxk/w622-h345-no/closebutton.PNG)

**Comment by vahidhedayati** [comment]
heh :) ye join the club - scratching my head on that for a long time too.. At the moment the hack is to refresh the page which destroys boxes but also closes down all other pm boxes. 

There are some underlying bugs with how I use this pm box possibly down to my usage/declaration of the dynamic boxes.

Will take another look at it when I have some time

**Comment by akiong** [comment]
oh i see...thank you...

**Comment by vahidhedayati** [comment]
will leave open until I have some form of resolution

**Comment by vahidhedayati** [comment]
This issue should now be rectified in 3.0.11, I have reverted back to the original jquery.ui.chatbox.js and it appears to work a lot better. There is obviously issues with the older version that did some other stuff around webcam notification.

**Comment by vahidhedayati** [comment]
This should now be fixed and overlapping pm boxes should also be fixed. There is also going to be a delete function as part of 3.016 release. I don't think this has been an issue for a while if it still is please re-open
