### ISSUE TITLE
i18n.gsp var enableCam conflicted with function enableCam function

### ISSUE THREAD

**Issue by zeneye** [vahidhedayati/grails-wschat-plugin#14]
so can not run enableCam function, console log it is not function

**Comment by vahidhedayati** [comment]
Thanks will sort this later and will be part of 3.011 release

**Comment by vahidhedayati** [comment]
3.0.11 has just been released, please test let me know if it is still an issue for you

**Comment by vahidhedayati** [comment]
I think this is not an issue I will close it please re-open or create a new issue if you still feel there is an issue
