### ISSUE TITLE
private message prolem

### ISSUE THREAD

**Issue by jerrylin1022** [vahidhedayati/grails-wschat-plugin#23]
Hi, in version 1.31, I find a problem in private message.
My username is "user01", and I send private message "hey" to username "admin", the result in "user01" should be "user01:hey", but the screenshot is 
![pm1 31](https://cloud.githubusercontent.com/assets/17740248/13867686/7dd7e184-ecfc-11e5-811e-387414a96de4.png)

In the previous version 1.26, the result is correct as below
![pm1 26](https://cloud.githubusercontent.com/assets/17740248/13867750/39464f8c-ecfd-11e5-9834-34a6dd3271d2.png)

How can I solve this problem?

**Comment by vahidhedayati** [comment]
Thank you Please try 1.31-SNAPSHOT1

**Comment by jerrylin1022** [comment]
I try it, and it's ok, thanks.
