### ISSUE TITLE
admin menu page status

### ISSUE THREAD

**Issue by rhodebump** [vahidhedayati/grails-wschat-plugin#6]
I have installed the plugin to grails 2.4, and configured it to run without security.

When I go to the admin menu page, there are a few links, but it doesn't seem that it is functional.
Here is the URL that i am using:
http://localhost:8080/myapp/wsChat/adminMenu

Here are the items that I see:
    Admin Options
    DB Console
    View Users
    Create Conference

What is strange is that the html does not have any head/body/ tags in the dom of the admin page.

Is this how to get to admin page, or is there a different URL that we should use?

Thanks for your hard work!

**Comment by vahidhedayati** [comment]
You need to s the the administration permission for  the user's globally in you config groovy  or your user https://github.com/vahidhedayati/grails-wschat-plugin/wiki/Creating-admin-accounts  once at when you log into chat there should be a cog at the top above chat room that is your administration menu.

Of you are administered but can't see the cog try  refresh page or goto another  room.

The administration menu  is that cog above chat room hence why html is not what you expected 

Sorry  for any typos mobile spell checker is ruthlessly incorrect

**Comment by vahidhedayati** [comment]
I hope you figured it out. Will close it re-open it if you are still having issues with the admin interface
